import PhysicalInternetVerifiedScalability

#print axioms PhysicalInternet.exact_supported_release_implies_dual_sufficiency
#print axioms PhysicalInternet.verified_scalable_federation_requires_dual_sufficiency
#print axioms PhysicalInternet.CommonFrame.common_frame_all_loops_are_identity
#print axioms PhysicalInternet.LinkedTrace.linked_trace_preserves_invariant
#print axioms PhysicalInternet.FieldNecessity.every_accountability_field_is_necessary
#print axioms PhysicalInternet.executed_world_is_safe
#print axioms PhysicalInternet.common_kernel_and_accountability_suffice_under_typed_assumptions
